utils/nvme: Add support for sanitize based WipeDisk
metal-toolbox/ironlib pull request #142
Opened 2024-05-07 15:07 UTC by mmlb

### What does this PR do

Adds support for wiping nvme disks using nvme format for those devices that do not support sanitize.

2024-05-07 15:07 UTC, mmlb commented
depends on #142

2024-05-08 14:13 UTC, joelrebel commented
> depends on #142

cyclic dependency alert!

2024-05-16 16:52 UTC, turegano-equinix requested changes
we need to check if err is nil here

https://github.com/metal-toolbox/ironlib/pull/142/files#diff-fd841c72621ce6171ce69fa396aa58dff324510ec8b41655a9d029abbad2176eR247-R251

2024-05-17 08:20 UTC, turegano-equinix approved these changes

2024-05-17 08:20 UTC, merged