Utility environment lookup, attributes
metal-toolbox/ironlib pull request #66
Opened 2022-11-25 15:25 UTC by joelrebel

### What does this PR do

- Defines environment variables that can be exported by users to override utility path.
- Updates all utilities to export attributes - name, absolute path and validation on the executable.
- Exports the `CheckDependencies()` method which can be used by a caller to verify utilities available.

![Screenshot 2022-11-25 at 16 07 22](https://user-images.githubusercontent.com/1710121/204015335-8f50e110-24d9-4fca-8b57-9f41162f8e5d.png)

2022-11-28 14:01 UTC, joelrebel commented
pushed commit that updates all deps and Go to 1.19.

2022-11-28 19:12 UTC, splaspood requested changes

2022-11-29 08:49 UTC, joelrebel commented on README.md
> +UTIL_ASRR_BIOSCONTROL
thats a good suggestion, pushed commit with the change.

2022-11-29 15:12 UTC, splaspood approved these changes

2022-11-29 15:13 UTC, merged